spring.application.name=config-server
server.port=8762

spring.profiles.active=native
spring.cloud.compatibility-verifier.enabled=false

spring.cloud.config.server.native.search-locations=classpath:/configs

eureka.instance.hostname=${EUREKA_HOSTNAME:localhost}
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:8761/eureka/

management.endpoints.web.exposure.include=health,info
